### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by AlexanderBabel** [dokku/docker-s3backup#28]
Hey,

I would like to see arm64 support for this image. I use it in a Kubernetes context for my backup strategy. For example I use k3s on a Raspberry Pi 4.

Therefore I build my own image with arm64 support and I would be really glad to add this to the base image. Unfortunately, building of the image is not done through GitHub Actions. But I wrote a small GitHub Workflow that takes care of this. 

I don't know if this could fit in your workflow or not, therefore I propose this feature here.

I would be very happy to hear some feedback on this matter and maybe it is possible to adjust your workflow.

My current version of the GitHub Workflow file can be found here: https://github.com/AlexanderBabel/docker-s3backup/blob/master/.github/workflows/build.yml

Cheers!
Alex

**Comment by josegonzalez** [comment]
An MR adding support for building this image in github would be great as auto-builds is now a paid feature.

**Comment by AlexanderBabel** [comment]
Nice, thanks for the quick answer. I will create a PR for this. But someone from your team needs to set the environment variables for the docker account.

**Comment by josegonzalez** [comment]
I can handle that, just issue the MR and we'll take it from there.

**Comment by AlexanderBabel** [comment]
Fixed by #29

**Comment by AlexanderBabel** [comment]
@josegonzalez Do you have an estimate when a new release will be created and therefore a build will happen?

**Comment by josegonzalez** [comment]
Just triggered it.

**Comment by AlexanderBabel** [comment]
Works as intended. Thank you for the trigger!

![Screenshot 2021-09-15 at 21 24 56](https://user-images.githubusercontent.com/13570439/133496746-4e1db31a-4924-4da5-ae1c-39b6995dfe0c.png)
